language: node_js

node_js:
  - '8'

cache:
  directories:
    - node_modules

install:
  - npm install -g codecov
  - npm install -g eslint

before_script:
  - cd Source
  - npm install

script:
  - npm run lint
  - npm test
